resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/supriyadas13/Projects_SpringBoot.git
      branch: master
    check_every: 1m
  
  - name: user-service-image
    type: docker-image
    source:
      repository: 192.168.16.1:5005/user-services
      insecure_registries: ["192.168.16.1:5005"]
      tag: user-services
      username: admin
      password: admin

jobs:
  - name: user-service
    serial: true
    public: true
    plan:
      - get: repo
        trigger: true
      - task: deploy-image
        file: repo/concourse/deploy-image.yml
      - put: user-service-image
        params:
          file: target/spring-boot-maven-dockerised-0.0.1-SNAPSHOT.jar
          name: spring-boot-maven-dockerised-0.0.1-SNAPSHOT.jar
          build: repo